mod asteroid;
mod collector;
mod collisions;
mod constants;
mod entity;
mod fragment;
mod networking;
mod particle;
mod player;
mod projectile;
mod shield;
mod space;
mod space_callback;
mod spaceship;
mod traits;
mod utils;
mod visual_effects;
pub mod wire;

use crate::core::{constants as core_constants, resources};
pub use space::SpaceAdventure;
pub use space_callback::SpaceCallback;
pub use constants::HULL_BREACH_MESSAGE;
pub use player::{LocalPlayerView, PlayerOutcome, ShipLoadout};
use spaceship::SpaceshipEntity;
pub use spaceship::SpaceshipRole;
pub use traits::*;
use utils::Direction;
